name: Build AIO Linux ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:24.04
      options: --privileged

    steps:
      - name: Install Git
        run: apt update && apt install -y git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: apt update && apt install -y live-build sudo systemd

      - name: Build ISO
        run: chmod +x build.sh && ./build.sh
