name: Build AIO Linux ISO

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: sudo apt update && sudo apt install -y live-build

      - name: Build ISO
        run: chmod +x build.sh && ./build.sh
